### ISSUE TITLE
Updating the Imiq database version number

### ISSUE THREAD

**Issue by grimm** [gina-alaska/imiq-api#50]
Currently there are only two records in the imiqversion table:

[#<Imiqversion versionnumber: "1.0", creationdate: "2014-07-07 10:08:39", versiondescription: "Contains data 62 and north for NCDC ISH and GHCN. ...">, #<Imiqversion versionnumber: "1.1", creationdate: "2015-05-19 13:24:00", versiondescription: "Contains data for the entire state of Alaska. New ...">]

This should be done each time we add new data?

**Comment by rwspicer** [comment]
Were doing this now
